Разметка главной страницы
htmlacademy-adaptive/1752767-pink-23 pull request #2
Opened 2021-07-24 09:12 UTC by Whireless

Разметка главной для мобильных устройств

2021-07-25 08:49 UTC, andreysgra requested changes

2021-07-25 08:49 UTC, andreysgra commented on source/index.html
> +        <img class="main-nav__logo" src="img/mobile/logo.svg" width="74" height="23" alt="Логотип всех логотипов">
https://up.htmlacademy.ru/adaptive/23/project/pink#pink-3-3 - тут написано, что на внутренних страницах, но для единообразия вёрстки стоит сделать ссылку и на главной странице.

2021-07-25 08:49 UTC, andreysgra commented on source/index.html
> +      <a class="main-header__button-download" href="#">Скачать приложение</a>
https://up.htmlacademy.ru/adaptive/23/project/pink#pink-4-2

2021-07-25 08:49 UTC, andreysgra commented on source/index.html
> +        <li class="main-header__platform-item--windows-phone"></li>
https://up.htmlacademy.ru/adaptive/23/project/pink#pink-4-3

2021-07-25 08:49 UTC, andreysgra commented on source/index.html
> +      </section>
Тегом `<section>`, как правило, размечают крупный смысловой раздел. Есть здесь такой? Нет. Если нужна обёртка над параграфом, то используйте `div`.

2021-07-25 08:49 UTC, andreysgra commented on source/index.html
> +        <div class="advantages__block-info--friends">
Ошибки БЭМ.

2021-07-25 08:49 UTC, andreysgra commented on source/index.html
> +        </table>
На мобильной версии часть таблицы скрыта (средствами CSS) - показана только центральная часть, но разметить всю таблицу нужно. Посмотрите планшетную и десктопную версии.

2021-07-25 08:49 UTC, andreysgra commented on source/index.html
> +        <div class="main-footer__footer-logo"></div>
Ссылка.

2021-07-25 08:49 UTC, andreysgra commented on source/index.html
> +        <p class="main-footer__who-develop">Разработано</p>
Вот этот элемент интерфейса - ссылка:
![image](https://user-images.githubusercontent.com/17790771/126893284-079bc9c9-4659-440c-93cd-7fad82039607.png)

Есть такой пункт ТЗ https://up.htmlacademy.ru/adaptive/23/project/pink#pink-3-8

2021-07-25 08:49 UTC, andreysgra commented on source/index.html
> +        <div class="about__about--adress">
Ошибки БЭМ.

2021-07-25 08:49 UTC, andreysgra commented on source/index.html
> +          <li class="main-footer__social-item--youtube"><a href="#"></a></li>
Ошибки БЭМ.

2021-07-25 15:37 UTC, Whireless commented on source/index.html
> +        <p class="main-footer__who-develop">Разработано</p>
Понял, изначально думал псевдо-элементом добавить изображение

2021-07-27 06:09 UTC, andreysgra requested changes

2021-07-27 06:09 UTC, andreysgra commented on source/index.html
> +      </nav>
А где же меню?
![image](https://user-images.githubusercontent.com/17790771/127104057-cb997cfa-ad23-48ec-8499-280588464a8c.png)

2021-07-27 06:09 UTC, andreysgra commented on source/index.html
> +        <a class="main-footer__footer-logo" href="https://htmlacademy.ru/intensive/adaptive"></a>
![image](https://user-images.githubusercontent.com/17790771/127104208-8f7c4bb3-5730-4540-b4db-a9f71643c601.png)
Это ссылка на главную страницу pink, а не на лендинг курса по вёрстке 😏

2021-07-27 15:59 UTC, merged